# Generated by Django 4.0.5 on 2022-07-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitallist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosptname', models.CharField(max_length=100, null=True)),
                ('contactno', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('A', 'active'), ('I', 'inactive')], max_length=1, null=True)),
                ('cdate', models.DateTimeField()),
                ('mdate', models.DateTimeField()),
                ('stateid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.states')),
            ],
        ),
    ]
