# Generated by Django 4.0.5 on 2022-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_hospitallist'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'active'), ('I', 'inactive')], max_length=1, null=True)),
                ('cdate', models.DateTimeField()),
                ('mdate', models.DateTimeField()),
            ],
        ),
    ]
