# Generated by Django 4.0.5 on 2022-07-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('A', 'active'), ('I', 'inactive')], max_length=1, null=True)),
                ('cdate', models.DateTimeField()),
                ('mdate', models.DateTimeField()),
                ('usertype', models.CharField(choices=[('D', 'doctor'), ('P', 'patient')], max_length=1, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.states')),
            ],
        ),
    ]
