# Generated by Django 4.0.5 on 2022-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='pword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
